# Best HPO Configuration - Trial 0
# Validation loss: inf
# Generated by Optuna HPO

# Data
dataset = "shakespeare_char"
batch_size = 32
block_size = 256
num_workers = 2
vocab_size = 0

# Model
n_layer = 2
n_head = 4
n_embd = 256
dropout = 0.0772550137268719
bias = False

# NeuroManifold features
use_sdr = True
sdr_size = 2048
manifold_dim = 64
n_eigenvectors = 32
use_kan = False
use_mhc = False
use_full_mhc = False
use_kaufmann_attention = False

# FHN settings
use_fhn_partitioning = False

# Training
max_iters = 100
gradient_accumulation_steps = 1
learning_rate = 0.0002787225221416519
min_lr = 1e-05
weight_decay = 0.1
warmup_iters = 20
lr_decay_iters = 100
grad_clip = 1.4835486051436413

# Early stopping
early_stopping_patience = 5

# Eval/logging
eval_interval = 25
log_interval = 10
eval_iters = 10
sample_interval = 500

# Output
save_checkpoints = False

# Hardware
devices = 1
precision = "bf16-mixed"
compile_model = False

# Logging
wandb_log = False

# Other parameters
sample_max_tokens = 100
sample_temperature = 1.0
sample_top_k = 40
